#!/bin/sh

OUTDIR="/usr/share/nginx/html/henrywalters.dev"

echo "Building henrywalters.dev frontend"

cd web

npm install
npm run build

echo "Syncing to outgoing dir: $OUTDIR"
  
rsync -a dist/ $OUTDIR

echo "Success"